import {
  LayoutDashboard,
  FolderKanban,
  Factory,
  Handshake,
  GitBranch,
  Boxes,
  DraftingCompass,
  Grid2x2,
  Layers,
  PackageOpen,
  Building2,
  ShieldCheck,
  TriangleAlert,
  BarChart3,
  Settings,
  Search,
  Bell,
  ChevronRight,
  ChevronDown,
  ArrowRight,
  ArrowLeft,
  X,
  Check,
  Plus,
  Upload,
  Download,
  ExternalLink,
  Clock,
  Calendar,
  CircleUser,
  Command,
  Filter,
  Lock,
  CornerDownRight,
  FileText,
  RefreshCw,
  TrendingUp,
  TrendingDown,
  CircleDot,
  Menu,
  type LucideProps,
} from 'lucide-react';

const MAP = {
  dashboard: LayoutDashboard,
  projects: FolderKanban,
  production: Factory,
  outsourcing: Handshake,
  bom: GitBranch,
  parts: Boxes,
  cadcam: DraftingCompass,
  nesting: Grid2x2,
  materials: Layers,
  inventory: PackageOpen,
  suppliers: Building2,
  qc: ShieldCheck,
  issues: TriangleAlert,
  analytics: BarChart3,
  settings: Settings,
  search: Search,
  bell: Bell,
  chevR: ChevronRight,
  chevD: ChevronDown,
  arrowR: ArrowRight,
  arrowL: ArrowLeft,
  x: X,
  check: Check,
  plus: Plus,
  upload: Upload,
  download: Download,
  ext: ExternalLink,
  clock: Clock,
  cal: Calendar,
  user: CircleUser,
  cmd: Command,
  filter: Filter,
  lock: Lock,
  cornerR: CornerDownRight,
  file: FileText,
  refresh: RefreshCw,
  trendUp: TrendingUp,
  trendDown: TrendingDown,
  dot: CircleDot,
  menu: Menu,
} as const;

export type IconName = keyof typeof MAP;

interface Props extends LucideProps {
  n: IconName | string;
}

export function Icon({ n, size = 16, strokeWidth = 1.6, ...rest }: Props) {
  const Cmp = MAP[n as IconName] ?? CircleDot;
  return <Cmp size={size} strokeWidth={strokeWidth} {...rest} />;
}
